DROP TABLE USUARIOS_CHAT CASCADE CONSTRAINTS;
DROP TABLE MENSAJES CASCADE CONSTRAINTS;
DROP TABLE USUARIOS CASCADE CONSTRAINTS;
DROP TABLE CHAT CASCADE CONSTRAINTS;


CREATE TABLE CHAT(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    fecha_creacion TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE USUARIOS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100),
    numero_telefono VARCHAR2(20) UNIQUE NOT NULL
);

CREATE TABLE MENSAJES(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    fecha_envio TIMESTAMP DEFAULT SYSTIMESTAMP,
    mensaje CLOB NOT NULL,
    id_usuario NUMBER REFERENCES USUARIOS(id) NOT NULL,
    id_chat NUMBER REFERENCES CHAT(id) NOT NULL
);

CREATE TABLE USUARIOS_CHAT(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id_usuarios NUMBER REFERENCES USUARIOS(id) NOT NULL,
    id_chat NUMBER REFERENCES CHAT(id) NOT NULL
);