--drop tablas usuario
DROP TABLE USUARIOS CASCADE CONSTRAINTS;
DROP TABLE PLANES_SUSCRIPCION CASCADE CONSTRAINTS;
DROP TABLE SUSCRIPCIONES CASCADE CONSTRAINTS;
DROP TABLE PAGOS CASCADE CONSTRAINTS;
DROP TABLE PERFILES CASCADE CONSTRAINTS;

--drop tablas categorias
DROP TABLE TIPO_CONTENIDOS CASCADE CONSTRAINTS;
DROP TABLE DEMOGRAFIAS CASCADE CONSTRAINTS;
DROP TABLE EDADES CASCADE CONSTRAINTS;
DROP TABLE GENEROS CASCADE CONSTRAINTS;
DROP TABLE TAGS CASCADE CONSTRAINTS;
DROP TABLE REGIONES CASCADE CONSTRAINTS;
DROP TABLE STUDIOS CASCADE CONSTRAINTS;

--drop tablas clasificacion
DROP TABLE CONTENIDOS CASCADE CONSTRAINTS;
DROP TABLE CONTENIDO_STUDIOS CASCADE CONSTRAINTS;
DROP TABLE CONTENIDO_GENEROS CASCADE CONSTRAINTS;
DROP TABLE CONTENIDO_TAGS CASCADE CONSTRAINTS;
DROP TABLE CONTENIDO_REGIONES CASCADE CONSTRAINTS;

--drop tablas episodios
DROP TABLE TEMPORADAS CASCADE CONSTRAINTS;
DROP TABLE EPISODIOS CASCADE CONSTRAINTS;
DROP TABLE SUBTITULOS CASCADE CONSTRAINTS;

--drop tablas interacciones
DROP TABLE FAVORITOS CASCADE CONSTRAINTS;
DROP TABLE HISTORIALES CASCADE CONSTRAINTS;



--TABLAS RELACIONADAS CON USUARIO
CREATE TABLE USUARIOS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    email_usuario VARCHAR2(100) UNIQUE NOT NULL,
    password_usuario VARCHAR2(100) NOT NULL,
    nombre_usuario VARCHAR2(100) NOT NULL,
    fecha_nacimiento DATE NOT NULL,
    fecha_registro TIMESTAMP DEFAULT SYSTIMESTAMP,
    usuario_activo BOOLEAN DEFAULT TRUE
);

CREATE TABLE PLANES_SUSCRIPCION(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre_plan VARCHAR2(100) NOT NULL,
    precio_plan NUMBER NOT NULL,
    dispositivos NUMBER NOT NULL,
    bloqueo_ads BOOLEAN DEFAULT FALSE,
    descarga_offline BOOLEAN DEFAULT FALSE,
    descripcion_plan CLOB
);

CREATE TABLE SUSCRIPCIONES(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER REFERENCES USUARIOS(id) NOT NULL,
    id_plan NUMBER REFERENCES PLANES_SUSCRIPCION(id) NOT NULL,
    fecha_inicio TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    fecha_termino DATE NOT NULL,
    estado VARCHAR2(20) DEFAULT 'activo' NOT NULL ,
    renovacion_automatica BOOLEAN DEFAULT TRUE

);

CREATE TABLE PAGOS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER REFERENCES USUARIOS(id) NOT NULL,
    id_suscripcion NUMBER REFERENCES SUSCRIPCIONES(id) NOT NULL,
    monto NUMBER NOT NULL,
    fecha_pago TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    metodo_pago VARCHAR2(50) NOT NULL,
    estado VARCHAR2(20) DEFAULT 'completado' NOT NULL ,
    id_transaccion VARCHAR2(100) UNIQUE NOT NULL
);

CREATE TABLE PERFILES(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER REFERENCES USUARIOS(id) NOT NULL,
    numbre_perfil VARCHAR2(100) NOT NULL,
    avatar_url VARCHAR2(500) NOT NULL,
    fecha_creacion TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

--TABLAS DE CLASIFICACIONES

CREATE TABLE TIPO_CONTENIDOS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre_tipo VARCHAR2(50) UNIQUE NOT NULL
);

CREATE TABLE DEMOGRAFIAS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre_demografia VARCHAR2(50) UNIQUE NOT NULL
);

CREATE TABLE EDADES(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    pg VARCHAR2(10) UNIQUE NOT NULL, -- EJEMPLO PG-13, PG-6, R
    descripcion CLOB NOT NULL,
    min_edad NUMBER NOT NULL

);

CREATE TABLE GENEROS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre_genero VARCHAR2(50) UNIQUE NOT NULL
);

CREATE TABLE TAGS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre_tags VARCHAR2(50) UNIQUE NOT NULL
);

CREATE TABLE REGIONES(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    codigo_region VARCHAR2(3) UNIQUE NOT NULL, --ejemplo US, JP, MX
    nombre_region VARCHAR2(100) NOT NULL
);

CREATE TABLE STUDIOS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre_studio VARCHAR2(100) UNIQUE NOT NULL,
    pais NUMBER REFERENCES REGIONES(id) UNIQUE NOT NULL,
    descipcion_studio CLOB NOT NULL,
    fecha_fundacion DATE NOT NULL,
    url_studio VARCHAR(500) UNIQUE NOT NULL

);

-- TABLAS RELACIONADAS CON CONTENIDOS

CREATE TABLE CONTENIDOS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id_tipo NUMBER REFERENCES TIPO_CONTENIDOS(id) NOT NULL,
    titulo_contenido VARCHAR(200) UNIQUE NOT NULL,
    titulo_original VARCHAR(200) UNIQUE NOT NULL,
    fecha_salida DATE NOT NULL,
    id_demografia NUMBER REFERENCES DEMOGRAFIAS(id) NOT NULL,
    id_studio NUMBER REFERENCES STUDIOS(id) NOT NULL,
    poster_url VARCHAR2(500) NOT NULL,
    banner_url VARCHAR2(500) NOT NULL,
    trailer_url VARCHAR2(500) NOT NULL,
    estado VARCHAR(50) DEFAULT 'en emision' NOT NULL  --EJEMPLO EN EMISION, TERMINADO
);

CREATE TABLE CONTENIDO_STUDIOS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id_contenido NUMBER REFERENCES CONTENIDOS(id) NOT NULL,
    id_studio NUMBER REFERENCES STUDIOS(id) NOT NULL,
    rol VARCHAR2(100) NOT NULL --EJEMPLO PRODUCCION, CO-PRODUCCION
);

CREATE TABLE CONTENIDO_GENEROS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id_contenido NUMBER REFERENCES CONTENIDOS(id) NOT NULL,
    id_genero NUMBER REFERENCES GENEROS(id) NOT NULL
);

CREATE TABLE CONTENIDO_TAGS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id_contenido NUMBER REFERENCES CONTENIDOS(id) NOT NULL,
    id_tag NUMBER REFERENCES TAGS(id) NOT NULL
);

CREATE TABLE CONTENIDO_REGIONES(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id_contenido NUMBER REFERENCES CONTENIDOS(id) NOT NULL,
    id_region NUMBER REFERENCES REGIONES(id) NOT NULL,
    disponible BOOLEAN DEFAULT TRUE -- TRUE= dispoble, FALSE= bloqueado

);

-- TABLAS RELACIONADAS A LOS EPISODIOS

CREATE TABLE TEMPORADAS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id_contenido NUMBER REFERENCES CONTENIDOS(id) NOT NULL,
    num_temporada NUMBER NOT NULL,
    nombre_temporada VARCHAR2(500) NOT NULL,
    fecha_inicio DATE NOT NULL,
    total_episodio NUMBER
);

CREATE TABLE EPISODIOS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id_contenido NUMBER REFERENCES CONTENIDOS(id) NOT NULL,
    id_temporada NUMBER REFERENCES TEMPORADAS(id),
    num_episodio NUMBER NOT NULL,
    nombre_episodio VARCHAR(100) UNIQUE NOT NULL,
    descripcion_episodio CLOB NOT NULL,
    duracion_episodio NUMBER NOT NULL,
    video_url VARCHAR2(500) UNIQUE NOT NULL,
    miniatura_url VARCHAR2(500) UNIQUE NOT NULL,
    fecha_lanzamiento DATE
);

CREATE TABLE SUBTITULOS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id_episodio NUMBER REFERENCES EPISODIOS(id) NOT NULL,
    codigo_sub VARCHAR(10) UNIQUE NOT NULL,
    nombre_sub VARCHAR(100) UNIQUE NOT NULL,
    sub_url VARCHAR(500) UNIQUE NOT NULL
);

--TABLAS INTERACCION CON USUARIOS

CREATE TABLE FAVORITOS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id_perfil NUMBER REFERENCES PERFILES(id) NOT NULL,
    id_contenido NUMBER REFERENCES CONTENIDOS(id) NOT NULL,
    fecha_favorito TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE HISTORIALES(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id_perfil NUMBER REFERENCES PERFILES(id) NOT NULL,
    id_contenido NUMBER REFERENCES CONTENIDOS(id) NOT NULL,
    fecha_historial TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    completado BOOLEAN DEFAULT FALSE
);





