DROP TABLE CATEGORIAS CASCADE CONSTRAINTS;
DROP TABLE PRODUCTO CASCADE CONSTRAINTS;
DROP TABLE TARJETA CASCADE CONSTRAINTS;
DROP TABLE TIPO_TARJETAS CASCADE CONSTRAINTS;
DROP TABLE PRODUCTO_CATEGORIAS CASCADE CONSTRAINTS;
DROP TABLE CODIGOS_AREA_PAIS CASCADE CONSTRAINTS;
DROP TABLE COMUNA CASCADE CONSTRAINTS;
DROP TABLE REGION CASCADE CONSTRAINTS;
DROP TABLE TARJETAS_USUARIOS CASCADE CONSTRAINTS;
DROP TABLE DOMICILIO CASCADE CONSTRAINTS;
DROP TABLE USUARIOS CASCADE CONSTRAINTS;
DROP TABLE USUARIOS_DOMICILIO CASCADE CONSTRAINTS;
DROP TABLE CARRITO CASCADE CONSTRAINTS;
DROP TABLE CARRITO_PRODUCTO CASCADE CONSTRAINTS;


CREATE TABLE CATEGORIAS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    nombre_categoria VARCHAR2(40)NOT NULL, 
    descripcion_categoria VARCHAR2(100)NOT NULL
);


CREATE TABLE PRODUCTO(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    nombre_producto VARCHAR2(40)NOT NULL, 
    descripcion_producto VARCHAR2(100)NOT NULL,
    valor_producto NUMBER(10,2)NOT NULL,
    tamaño_producto VARCHAR2(10)
);

CREATE TABLE TARJETA(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    nombre_titular VARCHAR2(40)NOT NULL,
    numero_tarjeta VARCHAR2(20) NOT NULL,
    digito_verificador NUMBER NOT NULL,
    fecha_vencimiento DATE,
    rut_titular VARCHAR2(13)NOT NULL
);

CREATE TABLE TIPO_TARJETAS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    tipo_tarjeta VARCHAR2(10) NOT NULL,
    id_tarjeta NUMBER REFERENCES TARJETA(id) NOT NULL
);

CREATE TABLE PRODUCTO_CATEGORIAS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    id_producto NUMBER REFERENCES PRODUCTO(id) NOT NULL,
    id_categoria NUMBER REFERENCES CATEGORIAS(id) NOT NULL
);

CREATE TABLE CODIGOS_AREA_PAIS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    nombre_dominio VARCHAR2(20) NOT NULL,
    codigo_area VARCHAR2(20) NOT NULL
);

CREATE TABLE COMUNA(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    nombre_comuna VARCHAR2(20) NOT NULL
);

CREATE TABLE REGION(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    nombre_region VARCHAR2(20) NOT NULL
);

CREATE TABLE DOMICILIO(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    calle_numero VARCHAR2(50) NOT NULL,
    id_region NUMBER REFERENCES REGION(id) NOT NULL,
    id_comuna NUMBER REFERENCES COMUNA(id) NOT NULL,
    departamento VARCHAR2(20),
    indicaciones VARCHAR2(128),
    tipo_domicilio VARCHAR2(12)NOT NULL

);

CREATE TABLE USUARIOS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    nombre_usuario VARCHAR2(50) NOT NULL,
    email_usuario VARCHAR2(100)NOT NULL UNIQUE,
    id_pais NUMBER REFERENCES CODIGOS_AREA_PAIS(id) NOT NULL,
    telefono_usuario VARCHAR2(15)NOT NULL,
    contraseña_usuario VARCHAR2(255)NOT NULL
);


CREATE TABLE CARRITO (
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    fecha TIMESTAMP DEFAULT SYSTIMESTAMP,
    id_usuario NUMBER REFERENCES USUARIOS(id) NOT NULL
);

CREATE TABLE CARRITO_PRODUCTO(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    id_carrito NUMBER REFERENCES CARRITO(id) NOT NULL,
    id_producto NUMBER REFERENCES PRODUCTO(id),
    cantidad NUMBER NOT NULL CHECK (cantidad >0)
);

CREATE TABLE TARJETAS_USUARIOS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    id_usuario NUMBER REFERENCES USUARIOS(id)NOT NULL,
    id_tarjeta NUMBER REFERENCES TARJETA(id)NOT NULL
);

CREATE TABLE USUARIOS_DOMICILIO(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    id_direccion NUMBER REFERENCES DOMICILIO(id)NOT NULL,
    id_usuario NUMBER REFERENCES USUARIOS(id)NOT NULL
);

-- INSERTS CATEGORIAS;

INSERT INTO CATEGORIAS (nombre_categoria, descripcion_categoria) VALUES
('Tecnología', 'Productos tecnológicos y electrónicos');

INSERT INTO CATEGORIAS (nombre_categoria, descripcion_categoria) VALUES
('Hogar', 'Artículos para el hogar');

INSERT INTO CATEGORIAS (nombre_categoria, descripcion_categoria) VALUES
('Moda', 'Ropa y accesorios');

INSERT INTO CATEGORIAS (nombre_categoria, descripcion_categoria) VALUES
('Deportes', 'Productos deportivos');

INSERT INTO CATEGORIAS (nombre_categoria, descripcion_categoria) VALUES
('Juguetes', 'Juguetes para niños');

-- INSERTS PRODUCTO;

INSERT INTO PRODUCTO (nombre_producto, descripcion_producto, valor_producto, tamaño_producto) VALUES
('Notebook HP', 'Notebook 16GB RAM', 850000, '15.6');

INSERT INTO PRODUCTO (nombre_producto, descripcion_producto, valor_producto, tamaño_producto) VALUES
('Silla Gamer', 'Silla ergonómica', 180000, 'Grande');

INSERT INTO PRODUCTO (nombre_producto, descripcion_producto, valor_producto, tamaño_producto) VALUES
('Polera Nike', 'Polera deportiva', 25000, 'M');

INSERT INTO PRODUCTO (nombre_producto, descripcion_producto, valor_producto, tamaño_producto) VALUES
('Bicicleta MTB', 'Bicicleta montaña', 320000, '27.5');

INSERT INTO PRODUCTO (nombre_producto, descripcion_producto, valor_producto, tamaño_producto) VALUES
('Set Lego', 'Lego clásico', 45000, 'Caja');

--INSERTS EN PRODUCTO_CATEGORIAS

INSERT INTO PRODUCTO_CATEGORIAS (id_producto, id_categoria) VALUES (1, 1);
INSERT INTO PRODUCTO_CATEGORIAS (id_producto, id_categoria) VALUES (2, 1);
INSERT INTO PRODUCTO_CATEGORIAS (id_producto, id_categoria) VALUES (3, 3);
INSERT INTO PRODUCTO_CATEGORIAS (id_producto, id_categoria) VALUES (4, 4);
INSERT INTO PRODUCTO_CATEGORIAS (id_producto, id_categoria) VALUES (5, 5);

--INSERTS EN CODIGOS_AREA_PAIS;

INSERT INTO CODIGOS_AREA_PAIS (nombre_dominio, codigo_area) VALUES ('Chile', '+56');
INSERT INTO CODIGOS_AREA_PAIS (nombre_dominio, codigo_area) VALUES ('Argentina', '+54');
INSERT INTO CODIGOS_AREA_PAIS (nombre_dominio, codigo_area) VALUES ('Peru', '+51');
INSERT INTO CODIGOS_AREA_PAIS (nombre_dominio, codigo_area) VALUES ('Colombia', '+57');
INSERT INTO CODIGOS_AREA_PAIS (nombre_dominio, codigo_area) VALUES ('Mexico', '+52');

--INSERTS EN REGION

INSERT INTO REGION (nombre_region) VALUES ('Metropolitana');
INSERT INTO REGION (nombre_region) VALUES ('Valparaíso');
INSERT INTO REGION (nombre_region) VALUES ('Biobío');
INSERT INTO REGION (nombre_region) VALUES ('Araucanía');
INSERT INTO REGION (nombre_region) VALUES ('Los Lagos');

--INSERTS EN COMUNA;

INSERT INTO COMUNA (nombre_comuna) VALUES ('Santiago');
INSERT INTO COMUNA (nombre_comuna) VALUES ('Providencia');
INSERT INTO COMUNA (nombre_comuna) VALUES ('Viña del Mar');
INSERT INTO COMUNA (nombre_comuna) VALUES ('Concepción');
INSERT INTO COMUNA (nombre_comuna) VALUES ('Puerto Montt');

--INSERTS EN DOMICILIO 

INSERT INTO DOMICILIO (calle_numero, id_region, id_comuna, departamento, indicaciones, tipo_domicilio)
VALUES ('Av. Alameda 123', 1, 1, '101', 'Edificio azul', 'Departamento');

INSERT INTO DOMICILIO VALUES (DEFAULT,'Providencia 456',1,2,NULL,'Cerca metro','Casa');
INSERT INTO DOMICILIO VALUES (DEFAULT,'Av. Marina 789',2,3,'202','Vista al mar','Departamento');
INSERT INTO DOMICILIO VALUES (DEFAULT,'Orompello 321',3,4,NULL,'Portón negro','Casa');
INSERT INTO DOMICILIO VALUES (DEFAULT,'Cardonal 654',5,5,NULL,'Frente supermercado','Casa');

--INSERT EN USUARIOS

INSERT INTO USUARIOS (nombre_usuario, email_usuario, id_pais, telefono_usuario, contraseña_usuario)
VALUES ('Juan Perez','juan@mail.cl',1,'912345678','hash123');

INSERT INTO USUARIOS VALUES (DEFAULT,'Maria Lopez','maria@mail.cl',1,'923456789','hash456');
INSERT INTO USUARIOS VALUES (DEFAULT,'Carlos Soto','carlos@mail.cl',2,'987654321','hash789');
INSERT INTO USUARIOS VALUES (DEFAULT,'Ana Diaz','ana@mail.cl',3,'956789123','hash321');
INSERT INTO USUARIOS VALUES (DEFAULT,'Pedro Rojas','pedro@mail.cl',1,'934567890','hash654');


--INSERT EN TAJETA

INSERT INTO TARJETA (nombre_titular, numero_tarjeta, digito_verificador, fecha_vencimiento, rut_titular)
VALUES ('Juan Perez','1111222233334444',123,TO_DATE('2027-05','YYYY-MM'),'12.345.678-9');

INSERT INTO TARJETA VALUES (DEFAULT,'Maria Lopez','5555666677778888',456,TO_DATE('2028-08','YYYY-MM'),'11.222.333-4');
INSERT INTO TARJETA VALUES (DEFAULT,'Carlos Soto','9999000011112222',789,TO_DATE('2026-12','YYYY-MM'),'9.876.543-2');
INSERT INTO TARJETA VALUES (DEFAULT,'Ana Diaz','3333444455556666',321,TO_DATE('2029-03','YYYY-MM'),'15.555.666-7');
INSERT INTO TARJETA VALUES (DEFAULT,'Pedro Rojas','7777888899990000',654,TO_DATE('2025-10','YYYY-MM'),'18.888.999-1');

--INSERT EN TIPO_TARJETAS
INSERT INTO TIPO_TARJETAS (tipo_tarjeta, id_tarjeta) VALUES ('VISA',1);
INSERT INTO TIPO_TARJETAS VALUES (DEFAULT,'MASTERCARD',2);
INSERT INTO TIPO_TARJETAS VALUES (DEFAULT,'VISA',3);
INSERT INTO TIPO_TARJETAS VALUES (DEFAULT,'DEBITO',4);
INSERT INTO TIPO_TARJETAS VALUES (DEFAULT,'VISA',5);

--INSERTS EN USUARIOS_TARJETAS
INSERT INTO USUARIOS_TARJETAS (id_usuario, id_tarjeta) VALUES (1,1);
INSERT INTO USUARIOS_TARJETAS VALUES (DEFAULT,2,2);
INSERT INTO USUARIOS_TARJETAS VALUES (DEFAULT,3,3);
INSERT INTO USUARIOS_TARJETAS VALUES (DEFAULT,4,4);
INSERT INTO USUARIOS_TARJETAS VALUES (DEFAULT,5,5);

--INSERT EN CARRITO

INSERT INTO CARRITO (id_usuario) VALUES (1);
INSERT INTO CARRITO (id_usuario) VALUES (2);
INSERT INTO CARRITO (id_usuario) VALUES (3);
INSERT INTO CARRITO (id_usuario) VALUES (4);
INSERT INTO CARRITO (id_usuario) VALUES (5);

--INSERT EN CARRITO_PRODUCTO
INSERT INTO CARRITOS_PRODUCTOS (id_carrito, id_producto, cantidad) VALUES (1,1,1);
INSERT INTO CARRITOS_PRODUCTOS VALUES (DEFAULT,1,3,2);
INSERT INTO CARRITOS_PRODUCTOS VALUES (DEFAULT,2,2,1);
INSERT INTO CARRITOS_PRODUCTOS VALUES (DEFAULT,3,4,1);
INSERT INTO CARRITOS_PRODUCTOS VALUES (DEFAULT,4,5,3);

--INSERT EN USUARIOS_DOMICILIO
INSERT INTO USUARIOS_DOMICILIO (id_direccion, id_usuario) VALUES (1,1);
INSERT INTO USUARIOS_DOMICILIO VALUES (DEFAULT,2,2);
INSERT INTO USUARIOS_DOMICILIO VALUES (DEFAULT,3,3);
INSERT INTO USUARIOS_DOMICILIO VALUES (DEFAULT,4,4);
INSERT INTO USUARIOS_DOMICILIO VALUES (DEFAULT,5,5);


