DECLARE

    v_nombre USUARIOS.NOMBRE_USUARIO%tYPE;

BEGIN

    SELECT NOMBRE_USUARIO INTO v_nombre FROM USUARIOS WHERE ID = 99;
    DBMS_OUTPUT.PUT_LINE('El usuario es:'|| v_nombre);

EXCEPTION

    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('ERROR');

    WHEN ZERO_DIVIDE THEN
    DBMS_OUTPUT.PUT_LINE('oLA');

END;