-- Necesitamos una tabla de auditoría primero
CREATE TABLE AUDIT_MENSAJES (
    id_log NUMBER GENERATED ALWAYS AS IDENTITY,
    mensaje_original CLOB,
    fecha_borrado TIMESTAMP DEFAULT SYSTIMESTAMP,
    usuario_borro VARCHAR2(100)
);

CREATE OR REPLACE TRIGGER TRG_AUDIT_DEL_MENSAJE
AFTER UPDATE ON MENSAJES
FOR EACH ROW
BEGIN
    SELECT * FROM USUARIOS WHERE ID = ID
COMMIT;
END;
/


SELECT * FROM AUDIT_MENSAJES;

DELETE FROM MENSAJES WHERE ID = 2;

ROLLBACK;

SELECT * FROM MENSAJES WHERE ID = 2;



